---

- hosts: all
  become: true
  tasks:

  - name: Update repository index then install latest apache and PHP packages.
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package  }}"
      state: latest
      update_cache: yes
