---

- hosts: all
  become: true
  tasks:

  - name: update repository index then install apache2 package
    ansible.builtin.apt:
      update_cache: yes
      name: apache2
      state: latest

  - name: Add PHP support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
