---

- hosts: all
  become: true
  tasks:

  - name: Update repository index then install latest apache2 package and PHP support for apache on Ubuntu and Debian
    ansible.builtin.apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

      
    # ---------------------------------- RedHat ---------------------------- #
  - name: Update repository index then install latest apache2 package and PHP support for apache on RedHat
    ansible.builtin.yum:
      update_cache: yes
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

