---

- hosts: all
  become: true
  tasks:

  - name: Remove apache2 package
    ansible.builtin.apt:
      name: apache2
      state: absent

  - name: Remove PHP support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
