---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates on Ubuntu and Debian.
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: Install updates on RedHat
    package:
      update_only: yes 
      update_cache: yes 
    when: ansible_distribution == "RedHat"

- hosts: web_servers
  become: true 
  tasks:

  - name: Install latest apache and PHP on web_servers.
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
    state: latest


- hosts: db_servers
  become: true 
  tasks:

  - name: Install latest mariaDB on db_servers.
    package:
      - "{{ db_name }}"
    state: latest