---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates on Ubuntu and Debian.
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: Install updates on RedHat
    tags: always
    package:
      update_only: yes 
      update_cache: yes 
    when: ansible_distribution == "RedHat"

# ---------------- web_servers ---------------- #
- hosts: web_servers
  become: true 
  tasks:

  - name: Install latest apache and PHP on web_servers
    tags: apache,apache2,httpd,php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: Copy default HTML file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


# ----------------- db_servers ----------------- #
- hosts: db_servers
  become: true 
  tasks:

  - name: Install latest mariaDB on db_servers
    tags: db,mariadb
    package:
      name:
        - "{{ db_name }}"
      state: latest


# ----------------- file_servers ----------------- #
- hosts: file_servers
  become: true
  tasks:

  - name: Install latest samba package on file_servers
    tags: samba
    package:
      name:
        - samba
      state: latest