---

- hosts: all
  become: true
  pre_tasks:

  - name: Update repository index and Install updates on Ubuntu and Debian
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: Update repository index and Install updates on RedHat and CentOS
    tags: always
    package:
      update_only: yes 
      update_cache: yes 
    when: ansible_distribution in ["RedHat", "CentOS"]
  
    # ----------- Make sure public key is added to sudoer user from bootstrap -------------- #
  # so you can connect to that machine using that user as he has the public key
  - name: Add SSH Public Key for simone user in authorized_key file
    tags: always,ssh
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPwOZz/n5jW93L8xx9jTAQMtcZgtMOKxjFGVjYW/N8/o Ansible"
      state: present  # Ensures the key is added if it's not already there to avoid duplicates.


# ---------------- workstations ---------------- #
- hosts: workstations
  become: true 
  tasks:

  - name: Install unzip
    package: 
      name:
        - unzip
      state: latest
  
#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicrop.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      mode: 0755
#      owner: root
#      group: root



# ---------------- web_servers ---------------- #
- hosts: web_servers
  become: true 
  tasks:

  - name: Install latest apache and PHP on web_servers
    tags: apache,apache2,httpd,php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: Copy default HTML file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
  # Start apache or httpd ------
  - name: Start httpd on RedHat and CentOS
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: Start apache2 on Ubuntu and Debian
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
  

  # change email address for admin and register result (changed, ok, or failed) in a variable called httpd ------
  - name: change email address for admin for RedHat and CentOS
    tags: apache,centos,httpd,redhat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regex: '^ServerAdmin'
      line: ServerAdmin ezzat22hegazy@gmail.com
    when: ansible_distribution in ["RedHat", "CentOS"]
    register: httpd


  # restart apache or httpd if email changed (httpd variable) ------
  - name: restart httpd 
    service:
      name: httpd
      state: restarted
    when: httpd.changed



# ----------------- db_servers ----------------- #
- hosts: db_servers
  become: true 
  tasks:

  - name: Install latest mariaDB on db_servers
    tags: db,mariadb
    package:
      name:
        - "{{ db_name }}"
      state: latest


# ----------------- file_servers ----------------- #
- hosts: file_servers
  become: true
  tasks:

  - name: Install latest samba package on file_servers
    tags: samba
    package:
      name:
        - samba
      state: latest