- name: Install latest apache and PHP on web_servers
  tags: apache,apache2,httpd,php
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest

- name: Copy default HTML file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

# Start apache or httpd ------
- name: Start httpd on RedHat and CentOS
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["RedHat", "CentOS"]

- name: Start apache2 on Ubuntu and Debian
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]


# change email address for admin and register result (changed, ok, or failed) in a variable called httpd ------
- name: change email address for admin for RedHat and CentOS
  tags: apache,centos,httpd,redhat
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin ezzat22hegazy@gmail.com
  when: ansible_distribution in ["RedHat", "CentOS"]
  register: httpd


# restart apache or httpd if email changed (httpd variable) ------
- name: restart httpd 
  service:
    name: httpd
    state: restarted
  when: httpd.changed