    # ----------- Make sure public key is added to sudoer user from bootstrap -------------- #
  # so you can connect to that machine using that user as he has the public key
  # Still leave it here although it exists in the boostrap, so you can have Key Management (eg: change the key)
- name: Add SSH Public Key for simone user in authorized_key file
  tags: always,ssh
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPwOZz/n5jW93L8xx9jTAQMtcZgtMOKxjFGVjYW/N8/o Ansible"
    state: present  # Ensures the key is added if it's not already there to avoid duplicates.

